#!/bin/bash
# =============================================================================
# setup-server.sh — First-time VPS setup for Chicken Shop Backend
# Run this ONCE on the VPS as user: jaber
#   scp scripts/setup-server.sh jaber@155.117.41.196:~/
#   ssh jaber@155.117.41.196 "bash ~/setup-server.sh"
# =============================================================================
set -e

APP_DIR="/home/jaber/chicken-app/backend"
NODE_MIN="18"

echo ""
echo "=================================================="
echo "  Chicken Shop Backend — First-time Server Setup"
echo "=================================================="
echo ""

# ── 1. Check Node.js ──────────────────────────────────────────────────────────
echo "[1/5] Checking Node.js..."
NODE_VER=$(node -v 2>/dev/null | sed 's/v//' | cut -d. -f1 || echo "0")
if [ "$NODE_VER" -lt "$NODE_MIN" ]; then
  echo "  Node.js $NODE_MIN+ is required. Installing via NodeSource..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi
echo "  Node.js $(node -v) — OK"

# ── 2. Install PM2 ────────────────────────────────────────────────────────────
echo ""
echo "[2/5] Installing PM2..."
if ! command -v pm2 &>/dev/null; then
  sudo npm install -g pm2
  pm2 startup systemd -u jaber --hp /home/jaber | tail -1 | sudo bash
fi
echo "  PM2 $(pm2 -v) — OK"

# ── 3. Create app directories ─────────────────────────────────────────────────
echo ""
echo "[3/5] Creating directories..."
mkdir -p "$APP_DIR/data"
mkdir -p "$APP_DIR/prisma"
echo "  Directories created at $APP_DIR"

# ── 4. Create .env file ───────────────────────────────────────────────────────
ENV_FILE="$APP_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "[4/5] Creating .env file..."
  JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")
  cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-server.sh
NODE_ENV=production
PORT=3000

DATABASE_URL="file:$APP_DIR/data/chicken_shop.db"
BACKUP_META_DATABASE_URL="file:$APP_DIR/data/backup-meta.db"
BACKUP_SCHEDULE_CRON="0 2 * * *"

LOG_LEVEL=info
JWT_SECRET=$JWT_SECRET
EOF
  echo "  .env created at $ENV_FILE"
  echo "  JWT_SECRET auto-generated"
else
  echo ""
  echo "[4/5] .env already exists — skipping"
fi

# ── 5. Firewall: open port 3000 ───────────────────────────────────────────────
echo ""
echo "[5/5] Opening firewall port 3000..."
if command -v ufw &>/dev/null; then
  sudo ufw allow 3000/tcp && echo "  ufw: port 3000 open"
fi

echo ""
echo "=================================================="
echo "  Setup complete!"
echo "  Now run the deploy script from your Windows PC:"
echo "    .\\scripts\\deploy.ps1"
echo "=================================================="
echo ""
